apiVersion: batch/v1
kind: Job
metadata:
  name: tensorflow-package-builder
spec:
  template:
    spec:
      containers:
      - name: tensorflow-package-builder
        image: tensorflow-builder
        command: ["./generate_packages_script.sh"]
        volumeMounts:
        - mountPath: /code/tensorflow_pkg
          name: built-package-vo
      restartPolicy: Never
      volumes:
      - name: built-package-vo
        emptyDir: {}
  backoffLimit: 4

